export const ROUTERS = {
    USER: {
        HOME: "",
        PRODUCT: "product",
        CONTACT: "contact",
        LOGIN: "login",
        REGISTER: "register",
        CHANGEPASSWORD: "changepassword",
        REQUESTINVOICE: "requestinvoice",
        PROFILE: "profile",
        INSURANCEREGISTRATION: "InsuranceRegistration",
        DONDANGKY: "registrationForms",
        REQUESTINVOICE: "requestinvoice",
        PAY: "pay",
        INVOICEHISTORYPAGE: "invoiceHistory",
        INVOICEHISTORYDETAILPAGE: "invoiceHistory/detail",
        TRANSACTION: "transactions",

        STAFF: "staff",
        YEUCAUHOANTRA: "staff/requestrefund",
        DONDANGKY: "staff/registrationForms",
        ADDINSPACK: "staff/insurancePackManagement/add",
        INSURANCEPACKM: "staff/insurancePackManagement",
        INFOCUSTOMER: "staff/infoCustomer",
        FINANCIALREPORT: "staff/financialReport",

        ADMINADDNEWSTAFF: "admin/addnewstaff",
        CHECKONSTAFF: "admin/checkonstaff",
        HOMEPAGEADMIN: "admin",
    },
};
